#name: FailsWith(error)
# --
FailsWith(${1:exception_name})